export default function AppShell({ title, version, children }) {
  return (
    <div className="app-shell">
      <header className="hero">
        <p className="eyebrow">Generated by Project Agent</p>
        <h1>{title}</h1>
        <p>{version}</p>
      </header>
      <main>{children}</main>
    </div>
  );
}
